---

- name: Ensure config and data dirs exist
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0755
  with_items:
    - consul_config_dir
    - consul_data_dir
