---

- name: Check current version
  command: consul version -format=json
  changed_when: false
  register: consul_existing_version

- block:
    - name: Install consul
      include_tasks: install_consul.yml
  when: consul_version == (consul_existing_version.stdout | from_json).Version
