---

- name: Ensure users and groups exists
  include_tasks: user_group.yml

- name: Check if consul exists
  stat:
    path: "{{ consul_bin_path }}/consul"
  register: consul_bin_file

- name: Check current version
  command: "{{ consul_bin_path }}/consul version -format=json"
  changed_when: false
  register: consul_existing_version
  when: consul_bin_file.stat.exists

- block:
    - name: Install consul
      include_tasks: install_consul.yml
  when: not consul_bin_file.stat.exists or consul_version != (consul_existing_version.stdout | from_json).Version

- include_tasks: install_config.yml
