---

- name: Ensure consul groups exists
  group:
    name: "{{ consul_group }}"
    state: present

- name: Ensure consul user exists
  ansible.builtin.user:
    name: "{{ consul_user }}"
    group: "{{ consul_group }}"
    home: "{{ consul_config_dir }}"
    comment: "Consul user"
    system: true
    shell: /bin/false
