---

# Configurable params
nomad_version: 1.1.5
nomad_datacenter: dc1
nomad_encrypt_key: ""
nomad_role: "client"
nomad_ca_file: "{{ nomad_config_dir }}/nomad-agent-ca.pem"
nomad_cert_file: "{{ nomad_config_dir }}/{{ nomad_datacenter }}-{{ nomad_role }}-nomad-0.pem"
nomad_key_file: "{{ nomad_config_dir }}/{{ nomad_datacenter }}-{{ nomad_role }}-nomad-0-key.pem"
consul_enable_ui: true
consul_bind_addr: "{{ '{{' }} GetInterfaceIP \\\"{{ ansible_default_ipv4.interface }}\\\" {{ '}}' }}"
consul_client_addr: "0.0.0.0"
# Disable http and enable https. You also change other ports similarly
consul_ports:
  http: -1
  https: 8501

# Advanced params
nomad_arch_map:
  amd64: amd64
  x86_64: amd64
  armv7l: arm
  aarch64: arm64
  32-bit: "386"
  64-bit: amd64

nomad_config_dir: /etc/nomad.d
nomad_data_dir: /opt/nomad
nomad_systemd_dir: /etc/systemd/system

consul_advertise_addr: "{{ consul_bind_addr }}"

nomad_pkg_name: nomad_{{ nomad_version }}_linux_{{ nomad_arch_map[ansible_architecture] }}.zip
nomad_checksum_name: nomad_{{ nomad_version }}_SHA256SUMS
nomad_base_url: https://releases.hashicorp.com/nomad/{{ nomad_version }}
nomad_pkg_url: "{{ nomad_base_url }}/{{ nomad_pkg_name }}"
nomad_checksum_url: "{{ nomad_base_url }}/{{ nomad_checksum_name }}"
