---

# Configurable params
nomad_version: 1.3.1
nomad_datacenter: dc1
nomad_region: global
nomad_role: client
nomad_encrypt_key: ""

## Locations of tls files on source (controller).
## These will be copied to remote at nomad_*_src_file and placed at nomad_*_file
nomad_ca_src_file: ""
nomad_cert_src_file: ""
nomad_key_src_file: ""
nomad_ca_file: "{{ nomad_config_dir }}/nomad-agent-ca.pem"
nomad_cert_file: "{{ nomad_config_dir }}/{{ nomad_region }}-{{ 'server' if nomad_role != 'client' else 'client' }}-nomad-0.pem"
nomad_key_file: "{{ nomad_config_dir }}/{{ nomad_region }}-{{ 'server' if nomad_role != 'client' else 'client' }}-nomad-0-key.pem"

## Consul auto-bootstrap and service discovery. Locations of tls files on source (controller)
nomad_consul_enable: true
nomad_consul_address: "127.0.0.1:8501"
nomad_consul_ssl: true
## These will be copied to remote at nomad_consul_*_src_file and placed at nomad_consul_*_file
nomad_consul_ca_src_file: ""
nomad_consul_cert_src_file: ""
nomad_consul_key_src_file: ""
nomad_consul_ca_file: "{{ nomad_config_dir }}/consul-agent-ca.pem"
nomad_consul_cert_file: "{{ nomad_config_dir }}/{{ nomad_datacenter }}-cli-consul-0.pem"
nomad_consul_key_file: "{{ nomad_config_dir }}/{{ nomad_datacenter }}-cli-consul-0-key.pem"
nomad_consul_tags: []

## Bind addresses - control which interfaces nomad listenes to.
nomad_bind_addr: "{{ '{{' }} GetInterfaceIP \\\"{{ ansible_default_ipv4.interface }}\\\" {{ '}}' }}"
nomad_http_addr: "{{ nomad_bind_addr }}"
nomad_rpc_addr: "{{ nomad_bind_addr }}"
nomad_serf_addr: "{{ nomad_bind_addr }}"

## Advertise address - control which interfaces nomad advertises.
nomad_http_adv_addr: "{{ nomad_http_addr }}"
nomad_rpc_adv_addr: "{{ nomad_rpc_addr }}"
nomad_serf_adv_addr: "{{ nomad_serf_addr }}"

# Host volumes
# Warning:
# The users must create the required directories and are responsible
# to ensure volumes are in sync (e.x: NFS) on all the hosts.
# Otherwise jobs may not run as required.
nomad_host_volumes: []
#Example config
#nomad_host_volumes:
#  - name: my_vol
#    path: /some/path/on/client
#    read_only: true # or false
#    owner: root # (defaults to nomad_user)
#    group: root # (defaults to nomad_group)
#    mode: "0700" # (defaults to 0755) # Always use a string

# Host networks
nomad_host_networks: []
#Example config
#nomad_host_networks:
#  - name: my_net
#    cidr_or_interface: 10.10.10.0/24 or eth0
#    reserved_ports: [20, 80]
nomad_telemetry_enable: false
nomad_telemetry_collection_interval: 1s
nomad_telemetry_disable_hostname: true
nomad_telemetry_prometheus_metrics: true
nomad_telemetry_publish_allocation_metrics: true
nomad_telemetry_publish_node_metrics: true


# Advanced params
nomad_arch_map:
  amd64: amd64
  x86_64: amd64
  armv7l: arm
  aarch64: arm64
  32-bit: "386"
  64-bit: amd64

nomad_config_dir: /etc/nomad.d
nomad_data_dir: /opt/nomad
nomad_systemd_dir: /etc/systemd/system
nomad_systemd_restart_sec: 30

nomad_pkg_name: nomad_{{ nomad_version }}_linux_{{ nomad_arch_map[ansible_architecture] }}.zip
nomad_checksum_name: nomad_{{ nomad_version }}_SHA256SUMS
nomad_base_url: https://releases.hashicorp.com/nomad/{{ nomad_version }}
nomad_pkg_url: "{{ nomad_base_url }}/{{ nomad_pkg_name }}"
nomad_checksum_url: "{{ nomad_base_url }}/{{ nomad_checksum_name }}"
