---

- lineinfile:
    path: /proc/cmdline
    regexp: "(^|.* ){{ param }}($| .*)"
    state: absent
  check_mode: true
  register: param_check
  changed_when: false

- lineinfile:
    backrefs: true
    path: "{{ cmdline_file }}"
    regexp: "{{ params_regexp }}"
    line: '\1 {{ item }}"'
  when: param_check.found == 0
  notify: restart device