---

- name: Checking if {{ item }} already exists
  lineinfile:
    path: /proc/cmdline
    regexp: "(^|.* ){{ item }}( .*|$)"
    state: absent
  check_mode: true
  register: param_check
  changed_when: false

- block:
    - name: Removing {{ item }}
      lineinfile:
        path: "/boot/armbianEnv.txt"
        regexp: "^{{ item }}$"
        state: absent
      become: true
      notify: reboot device

    - name: Removing {{ item }} from extraargs
      lineinfile:
        backrefs: true
        path: "/boot/armbianEnv.txt"
        regexp: "^extraargs= *([^\\s](?: *[^\\s])*)? *{{ item }} *([^\\s](?: *[^\\s])*)?"
        line: 'extraargs=\1 \2'
      become: true
      notify: reboot device

    - name: Cleanup extraargs
      lineinfile:
        backrefs: true
        path: "/boot/armbianEnv.txt"
        regexp: "^extraargs= *([^\\s](?: *[^\\s])*)"
        line: 'extraargs=\1'
      become: true
      notify: reboot device

    - name: Remove extraaargs (if empty)
      lineinfile:
        path: "/boot/armbianEnv.txt"
        regexp: "^extraargs= *$"
        state: absent
      become: true
      notify: reboot device
  when: param_check.found > 0
