---

- name: Checking if {{ item }} present
  lineinfile:
    path: /proc/cmdline
    regexp: "(^|.* ){{ item }}( .*|$)"
    state: absent
  check_mode: true
  register: param_check
  changed_when: false

- block:
    - name: Checking if extraargs present
      lineinfile:
        path: /boot/armbianEnv.txt
        regexp: "^extraargs=.*"
        state: absent
      check_mode: true
      register: extraargs_check
      changed_when: false

    - name: Adding extraaargs
      lineinfile:
        backrefs: true
        path: "/boot/armbianEnv.txt"
        regexp: "^extraargs=.*$"
        line: 'extraargs={{ item }}'
      become: true
      when: extraargs_check.found == 0
      notify: restart device

    - name: Adding {{ item }}
      lineinfile:
        backrefs: true
        path: "/boot/armbianEnv.txt"
        regexp: "^extraargs= *( *[a-zA-Z._=])* *"
        line: 'extraargs=\1 {{ item }}'
      become: true
      when: extraargs_check.found > 0
      notify: restart device
  when: param_check.found == 0
