---

- name: boot_params_present and boot_params_absent must be mutually exclusive
  assert:
    that: boot_params_present | intersect(boot_params_absent) | length == 0

- name: Checking if Armbian type
  stat: path=/boot/armbianEnv.txt
  register: armbian_boot

- name: Checking if RPi type
  stat: path=/boot/firmware/cmdline.txt
  register: rpi_boot

- name: Type must be one of above
  assert:
    that: armbian_boot.stat.exists or rpi_boot.stat.exists

- block:
    - name: Params present | Armbian
      include: armbian_present.yml
      loop: "{{ boot_params_present }}"

    - name: Params absent | Armbian
      include: armbian_absent.yml
      loop: "{{ boot_params_absent }}"
  when: armbian_boot.stat.exists

- block:
    - name: Params present | RPi
      include: rpi_present.yml
      loop: "{{ boot_params_present }}"

    - name: Params absent | RPi
      include: rpi_absent.yml
      loop: "{{ boot_params_absent }}"
  when: rpi_boot.stat.exists

- name: Flush handlers
  meta: flush_handlers

- name: Verify if params present
  include: verify_present.yml
  loop: "{{ boot_params_present }}"
  when:
    - boot_params_present | length > 0
    - verify_present | bool

- name: Verify if params absent
  include: verify_absent.yml
  loop: "{{ boot_params_absent }}"
  when:
    - boot_params_absent | length > 0
    - verify_absent | bool
