---

- name: Checking if Armbian type
  stat: path=/boot/armbianEnv.txt
  register: armbian_boot

- name: Checking if RPi type
  stat: path=/boot/firmware/cmdline.txt
  register: rpi_boot

- name: Type must be one of above
  assert:
    that: armbian_boot.stat.exists or rpi_boot.stat.exists

- block:
    - include: param_present_armbian.yml
      loop: "{{ boot_params_present }}"

    - include: param_absent_armbian.yml
      loop: "{{ boot_params_absent }}"
  when: armbian_boot.stat.exists

- block:
    - include: param_present_rpi.yml
      loop: "{{ boot_params_present }}"

    - include: param_absent_rpi.yml
      loop: "{{ boot_params_absent }}"
  when: rpi_boot.stat.exists
