---

- name: Checking /boot/firmware/cmdline.txt
  stat: path=/boot/firmware/cmdline.txt
  register: rpi_boot

- name: Checking /boot/armbianEnv.txt
  stat: path=/boot/armbianEnv.txt
  register: amrbian_boot

- include: add_param.yml
  vars:
    cmdline_file: /boot/firmware/cmdline.txt
    params_regexp: "^(.*)$"
  loop: "{{ boot_params }}"
  no_log: true
  when: rpi_boot.stat.exists

- include: add_param.yml
  vars:
    cmdline_file: /boot/armbianEnv.txt
    params_regexp: "^extraargs=(.*)$"
  loop: "{{ boot_params }}"
  no_log: true
  when: amrbian_boot.stat.exists
