---

- name: Checking if {{ item }} already exists
  lineinfile:
    path: /proc/cmdline
    regexp: "(^|.* ){{ item }}( .*|$)"
    state: absent
  check_mode: true
  register: param_check
  changed_when: false

- block:
    - name: Removing {{ item }}
      lineinfile:
        backrefs: true
        path: "/boot/firmware/cmdline.txt"
        regexp: "([^\\s](?: *[^\\s])*)? *{{ item }} *([^\\s](?: *[^\\s])*)?"
        line: '\1 \2'
      become: true

    - name: Cleanup boot params
      lineinfile:
        backrefs: true
        path: "/boot/firmware/cmdline.txt"
        regexp: "([^\\s](?: *[^\\s])*)"
        line: '\1'
      become: true
  when: param_check.found > 0
  notify: reboot device
