---

# Configurable params
consul_version: 1.10.2

# Advanced params
consul_arch_map:
  amd64: amd64
  x86_64: amd64
  armv7l: arm
  aarch64: arm64
  32-bit: "386"
  64-bit: amd64
consul_pkg_name: consul_{{ consul_version }}_linux_{{ consul_arch_map[ansible_architecture] }}.zip
consul_checksum_name: consul_{{ consul_version }}_SHA256SUMS
consul_pkg_url: https://releases.hashicorp.com/consul/{{ consul_version }}/{{ consul_pkg_name }}
consul_checksum_url: https://releases.hashicorp.com/consul/{{ consul_version }}/{{ consul_checksum_name }}
