---

# Configurable params
consul_version: 1.10.2
consul_datacenter: dc1
consul_encrypt_key: ""
consul_ca_file: /etc/consul.d/consul-agent-ca.pem
consul_cert_file: /etc/consul.d/dc1-server-consul-0.pem
consul_key_file: /etc/consul.d/dc1-server-consul-0-key.pem
consul_role: server

# Advanced params
consul_arch_map:
  amd64: amd64
  x86_64: amd64
  armv7l: arm
  aarch64: arm64
  32-bit: "386"
  64-bit: amd64
consul_user: consul
consul_group: consul
consul_config_dir: /etc/consul.d
consul_data_dir: /opt/consul
consul_systemd_dir: /usr/lib/systemd/system
consul_pkg_name: consul_{{ consul_version }}_linux_{{ consul_arch_map[ansible_architecture] }}.zip
consul_checksum_name: consul_{{ consul_version }}_SHA256SUMS
consul_base_url: https://releases.hashicorp.com/consul/{{ consul_version }}
consul_pkg_url: {{ consul_base_url }}/{{ consul_pkg_name }}
consul_checksum_url: {{ consul_base_url }}/{{ consul_checksum_name }}
