---

# Configurable params
consul_version: 1.10.2
consul_datacenter: dc1
consul_encrypt_key: ""
consul_role: ""
consul_ca_file: "{{ consul_config_dir }}/consul-agent-ca.pem"
consul_cert_file: "{{ consul_config_dir }}/{{ consul_datacenter }}-{{ consul_role }}-consul-0.pem"
consul_key_file: "{{ consul_config_dir }}/{{ consul_datacenter }}-{{ consul_role }}-consul-0-key.pem"
consul_enable_ui: true
consul_bind_addr: "{{ '{{' }} GetInterfaceIP \\\"{{ ansible_default_ipv4.interface }}\\\" {{ '}}' }}"
consul_client_addr: "0.0.0.0"
# Disable http and enable https. You also change other ports similarly
consul_ports:
  http: -1
  https: 8501

# Advanced params
consul_arch_map:
  amd64: amd64
  x86_64: amd64
  armv7l: arm
  aarch64: arm64
  32-bit: "386"
  64-bit: amd64

consul_user: consul
consul_group: consul
consul_config_dir: /etc/consul.d
consul_data_dir: /opt/consul
consul_systemd_dir: /usr/lib/systemd/system

consul_advertise_addr: "{{ consul_bind_addr }}"

consul_pkg_name: consul_{{ consul_version }}_linux_{{ consul_arch_map[ansible_architecture] }}.zip
consul_checksum_name: consul_{{ consul_version }}_SHA256SUMS
consul_base_url: https://releases.hashicorp.com/consul/{{ consul_version }}
consul_pkg_url: "{{ consul_base_url }}/{{ consul_pkg_name }}"
consul_checksum_url: "{{ consul_base_url }}/{{ consul_checksum_name }}"
