---

- name: Ensure nomad groups exists
  become: true
  group:
    name: "{{ nomad_group }}"
    state: present
  when: nomad_group != "root"

- name: Ensure nomad user exists
  become: true
  ansible.builtin.user:
    name: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    comment: "Nomad user"
    system: true
    shell: /bin/false
  when: nomad_user != "root"
