---

- name: Ensure vault groups exists
  become: true
  group:
    name: "{{ vault_group }}"
    state: present

- name: Ensure vault user exists
  become: true
  ansible.builtin.user:
    name: "{{ vault_user }}"
    group: "{{ vault_group }}"
    comment: "Vault user"
    system: true
    shell: /bin/false
