---

- name: Check if data folder exists
  file:
    path: "{{ consul_data_dir }}"
    state: directory
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0755

- name: Check if config dir exists
  file:
    path: "{{ consul_config_dir }}"
    state: directory
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0755
  register: consul_hcl

- name: Slurp the file
  ansible.builtin.slurp:
    src: "{{ consul_config_dir }}/_consul.hcl"
  register: consul_hcl_content
  when: consul_hcl.stat.exists

- debug: var="consul_hcl_content"

- name: Check if encryption key is present
  set_fact:

- name: Check if encryption key is same for all
